import React, { useState } from 'react';
import { Calculator, Search, FileText, ArrowRight, TrendingUp, Calendar, MapPin, Building } from 'lucide-react';
import { useEstimateStore } from '@/store/estimateStore';
import { formatPrice } from '@/utils/formatPrice';
import { Link } from 'react-router-dom';

export const AdminEstimatesPage: React.FC = () => {
  const { estimates } = useEstimateStore();
  const [searchQuery, setSearchQuery] = useState('');

  const filteredEstimates = estimates.filter((est) =>
    est.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
    est.inputs.projectName?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    est.inputs.city?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    est.inputs.projectType.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl font-heading font-black text-slate-900">
              Construction Cost Estimates
            </h1>
            <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-slate-200 text-slate-700">
              {estimates.length} Generated
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Audit Smart Construction Cost Calculator estimates generated by clients and contractors
          </p>
        </div>
      </div>

      {/* Search */}
      <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-xs flex items-center gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search estimates by ID, project name, location..."
            className="w-full pl-10 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs sm:text-sm text-slate-900 focus:outline-none focus:border-accent"
          />
        </div>
      </div>

      {/* Estimates Table */}
      <div className="bg-white rounded-2xl border border-slate-200/80 overflow-hidden shadow-xs">
        <div className="overflow-x-auto">
          <table className="w-full border-collapse text-left text-xs">
            <thead>
              <tr className="bg-slate-50 text-slate-500 font-bold uppercase tracking-wider border-b border-slate-200">
                <th className="py-3.5 px-4">Estimate ID & Project</th>
                <th className="py-3.5 px-4">Type & Area</th>
                <th className="py-3.5 px-4">City / Location</th>
                <th className="py-3.5 px-4 text-right">Materials Total</th>
                <th className="py-3.5 px-4 text-right">Estimated Total</th>
                <th className="py-3.5 px-4 text-center">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredEstimates.map((est) => (
                <tr key={est.id} className="hover:bg-slate-50/70 transition-colors">
                  <td className="py-3.5 px-4">
                    <strong className="text-slate-900 font-bold block">{est.id}</strong>
                    <span className="text-slate-500 text-[11px]">
                      {est.inputs.projectName || 'Unnamed Estimate'}
                    </span>
                  </td>
                  <td className="py-3.5 px-4">
                    <span className="font-semibold text-slate-800 block">
                      {est.inputs.projectType} ({est.inputs.quality})
                    </span>
                    <span className="text-[11px] text-slate-500">
                      {est.inputs.builtUpArea} {est.inputs.areaUnit} • {est.inputs.floors} Floors
                    </span>
                  </td>
                  <td className="py-3.5 px-4">
                    <span className="inline-flex items-center gap-1 text-slate-600 font-medium">
                      <MapPin className="w-3 h-3 text-slate-400" />
                      <span>{est.inputs.city || 'Standard Zone'}</span>
                    </span>
                  </td>
                  <td className="py-3.5 px-4 text-right font-medium text-slate-700">
                    {est.materials.length} material lines
                  </td>
                  <td className="py-3.5 px-4 text-right">
                    <strong className="text-slate-900 font-bold block">
                      {formatPrice(est.totalAtEstimate)}
                    </strong>
                    <span className="text-[10px] text-slate-400">
                      +GST & Delivery incl.
                    </span>
                  </td>
                  <td className="py-3.5 px-4 text-center">
                    <Link
                      to={`/estimates/${est.id}`}
                      target="_blank"
                      className="inline-flex items-center gap-1 text-xs font-bold text-accent hover:underline"
                    >
                      <span>Inspect</span>
                      <ArrowRight className="w-3.5 h-3.5" />
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default AdminEstimatesPage;
